### PR TITLE
Save source file path and time stamp, and much more

### PR DESCRIPTION
**Pull request by drbig**
I originally wanted only 2. as I thought 4. was already there... anyways:

 1. Use Hash as the storage data type
 2. Save source file path and time stamp on saving
 3. Delete the data kept in storage when deleting from Imgurr
 4. Command for listing storage-kept data

This whole thing would IMHO appreciate some more love...

### CODE REVIEW

**Comment by Chris911** [comment]
Thanks for this. I'm busy with work but I'll take a look as soon as possible. As long as tests are still passing (and feel free to add some more if needed) this should be fine. 

If you'd like to work on this gem submit a few more PRs and I'll add you as a contributor if the quality is there.

**Comment by drbig** [comment]
Mhm the tests, right... I didn't touch these, so no rush with looking at this PR. I'll mark it as [WIP] for the time being.

**Comment by Chris911** [comment]
Just run: `rake test`

**Comment by drbig** [comment]
Right, I can't put it another way: the testing contraption you have there is madness. I've unbroken it as far as it was possible.

Some points: Unix-only, and I have doubts it'll even run on every Linux; The `it_uploads_image()` case was never able to fail; The test cases were hanging apparently doing nothing - adding `-m 1` to grep seems to fix the issue (why exactly? no idea); the `roundup_trace()` is just hilarious.

Was there any historical reason for you not to use a pure-Ruby testing framework? So that even Windows users can run test? And you can actually write detailed tests without doing crap like ```expr `cat ${id_file} | wc -c` ">" 0```?

**Comment by Chris911** [comment]
Tests where mostly inspired by Zach Holman's [boom](https://github.com/holman/boom) project. If I recall correctly he wrote a blog post about it and explained that he went for "black box" shell tests because even though the code is in Ruby it's only meant to be used a CLI utility and not a Ruby library. That made sense to me and I went with the same option (using `roundup` which is something I didn't build). 

However I agree that tests should run on any platform if the tool supports many platform and I never tried that. I develop on OSX and tests are still 100% on master right now running `rake test`.   

Thanks for looking into it.

**Comment by Chris911** [comment]
@drbig I'm getting the following error when running `imgurr list` with ruby 2.1.3p242. 

```
➜  imgurr git:(save-file-path-and-stamp) ruby bin/imgurr list
/Users/chris/Downloads/tmp/imgurr/lib/imgurr/storage.rb:68:in `block in items': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/chris/Downloads/tmp/imgurr/lib/imgurr/storage.rb:68:in `sort'
	from /Users/chris/Downloads/tmp/imgurr/lib/imgurr/storage.rb:68:in `items'
	from /Users/chris/Downloads/tmp/imgurr/lib/imgurr/command.rb:170:in `list'
	from /Users/chris/Downloads/tmp/imgurr/lib/imgurr/command.rb:113:in `delegate'
	from /Users/chris/Downloads/tmp/imgurr/lib/imgurr/command.rb:27:in `execute'
	from bin/imgurr:8:in `<main>'
```

**Comment by drbig** [comment]
Do you have a clean `$IMGURRFILE` (i.e. none or one made by the modified version)? If yes then it's probably something broken on my part and I'll look into that. Otherwise: should we include something to convert the old `.imgurr` to the new format?

The new format:

    {
      "hashes": {
        "HGPHUjA": {
          "deletehash": "Y1eg...",
          "source": "/home/drbig/Screenshot - 160115 - 23:15:34.png",
          "stamp": "2015-01-20 10:29:02 +0100"
        },
        "UT0UqRC": {
          "deletehash": "EyVg...",
          "source": "/home/drbig/Screenshot - 160115 - 23:05:33.png",
          "stamp": "2015-01-20 10:41:01 +0100"
        }
      }
    }⏎

**Comment by Chris911** [comment]
Indeed this is what I have: 
```
{
  "hashes": [
    {
      "id": "omeh..",
      "deletehash": "acS6Zbu..."
    },
    {
      "id": "7xXSe..",
      "deletehash": "NfYqvO..."
    },
    {
      "id": "OjwHP..",
      "deletehash": "NQpa..."
    }
  ]
}%
``` 

I like your new format but don't want to break compatibility with the existing file. If you are up for it please add a `convert` method or I'll do it at some point. Currently really busy at work and leaving for vacation soon so that's why it took me a while to look at this.

**Comment by drbig** [comment]
No rush, and enjoy your vacation.

I may add a patch here with the following logic: on loading JSON check for old file format and convert it to the new one with 'unknown' for `:source` and current date for `:stamp`, plus print a one time warning indicating that. And a test case for that... :)

**Comment by Chris911** [comment]
That's what I had in mind. Thanks for your contributions to this project.

**Comment by drbig** [comment]
That should do it. I'm not particularly happy with printing from `Imgurr::Storage`, but for the sake of simplicity that was the way to go. Also I'd treat the whole 'convert' business as temporary.

**Comment by Chris911** [comment]
All good. Thanks again for your work. If you're interested in maintaining this repo let me know. This was a weekend project a few years ago and while I still use it a lot I'm not actively developing it. 

Will release this as v1.0.0 and will use semver from now on.

**Pull request merged**
